YETKILI_ID = []
BOT_TOKEN = "<TELGRAM-APİ-KEY>"
ADMIN_SIFRE = "<TELEGRAM-ADMIN-SİFRE>"
İŞLEM_CİFTLERİ = ['BTCUSDT','ETHUSDT','ADAUSDT','BNBUSDT','XRPUSDT', 
                 'SOLUSDT','AVAXUSDT','TRXUSDT','USDTTRY']